export default {
  counts: [
    {
      primary: 'AB',
      secondary: ['Lethbridge', 'Red Deer', 'Calgary'],
      data: [
        {
          instrument: {
            ROUTING: 12,
            CONSTRUCTION: 11,
            ABANDONMENT: 1,
            OPENING: 22,
            MISC: 2,
            SAFETY: 9,
            TARIFFS: 11,
          },
          theme: {
            ADMINISTRATIVE: 10,
            DAMAGE_PREVENTION: 0,
            EMERGENCY_MANAGEMENT: 2,
            ENFORCEMENT: 5,
            ENVIRONMENTAL_PROTECTION: 3,
            FINANCIAL: 0,
            INTEGRITY_MANAGEMENT: 11,
            MANAGEMENT_SYSTEM: 2,
            SAFETY_MANAGEMENT: 7,
            SECURITY: 1,
            SOCIO_ECONOMIC: 11,
            STANDARD_CONDITION: 0,
            SUNSET_CLAUSE: 15,
          },
          phase: {
            ABANDONMENT: 2,
            DURING_CONSTRUCTION_PHASE: 7,
            EXPIRY_DATE_OF_REG_INSTR: 6,
            INCLUDES_ALL_PHASES_OF_CONSTR: 12,
            NOT_CONSTRUCTION_RELATED: 33,
            POST_CONSTRUCTION_PHASE: 4,
            PRIOR_TO_THE_CONSTRUCTION_PHASE: 2,
            UNSPECIFIED: 5,
          },
          status: {
            IN_PROGRESS: 1,
            CLOSED: 8,
          },
          type: {
            NON_STANDARD: 3,
            STANDARD: 11,
          },
          filing: {
            REQUIRED: 0,
            NOT_REQUIRED: 7,
          },
        },
      ],
    },
    {
      primary: 'SK',
      secondary: ['Saskatoon', 'Regina'],
      data: [
        {
          instrument: {
            ROUTING: 12,
            CONSTRUCTION: 11,
            ABANDONMENT: 1,
            OPENING: 22,
            MISC: 2,
            SAFETY: 9,
            TARIFFS: 11,
          },
          theme: {
            ADMINISTRATIVE: 10,
            DAMAGE_PREVENTION: 0,
            EMERGENCY_MANAGEMENT: 2,
            ENFORCEMENT: 5,
            ENVIRONMENTAL_PROTECTION: 3,
            FINANCIAL: 0,
            INTEGRITY_MANAGEMENT: 11,
            MANAGEMENT_SYSTEM: 2,
            SAFETY_MANAGEMENT: 7,
            SECURITY: 1,
            SOCIO_ECONOMIC: 11,
            STANDARD_CONDITION: 0,
            SUNSET_CLAUSE: 15,
          },
          phase: {
            ABANDONMENT: 2,
            DURING_CONSTRUCTION_PHASE: 7,
            EXPIRY_DATE_OF_REG_INSTR: 6,
            INCLUDES_ALL_PHASES_OF_CONSTR: 12,
            NOT_CONSTRUCTION_RELATED: 33,
            POST_CONSTRUCTION_PHASE: 4,
            PRIOR_TO_THE_CONSTRUCTION_PHASE: 2,
            UNSPECIFIED: 5,
          },
          status: {
            IN_PROGRESS: 1,
            CLOSED: 8,
          },
          type: {
            NON_STANDARD: 3,
            STANDARD: 11,
          },
          filing: {
            REQUIRED: 0,
            NOT_REQUIRED: 7,
          },
        },
      ],
    },
  ],
};
