export default {
  theme: [
    'ADMINISTRATIVE',
    'DAMAGE_PREVENTION',
    'EMERGENCY_MANAGEMENT',
    'ENFORCEMENT',
    'ENVIRONMENTAL_PROTECTION',
    'FINANCIAL',
    'INTEGRITY_MANAGEMENT',
    'MANAGEMENT_SYSTEM',
    'SAFETY_MANAGEMENT',
    'SECURITY',
    'SOCIO_ECONOMIC',
    'STANDARD_CONDITION',
    'SUNSET_CLAUSE',
  ],
  phase: [
    'ABANDONMENT',
    'DURING_CONSTRUCTION_PHASE',
    'EXPIRY_DATE_OF_REG_INSTR',
    'INCLUDES_ALL_PHASES_OF_CONSTR',
    'NOT_CONSTRUCTION_RELATED',
    'POST_CONSTRUCTION_PHASE',
    'PRIOR_TO_THE_CONSTRUCTION_PHASE',
    'UNSPECIFIED',
  ],
  status: [
    'CLOSED',
    'IN_PROGRESS',
  ],
  type: [
    'STANDARD',
    'NON_STANDARD',
  ],
  filing: [
    'REQUIRED',
    'NOT_REQUIRED',
  ],
  instrument: [
    'MO',
    'AO',
    'XG',
    'XO',
    'ZO',
    'OPL',
    'SG',
    'SO',
    'GC',
    'OTHER',
  ],
  instrumentOther: [
    'EC',
    'EP',
    'EPE',
    'FRO',
    'GPLO',
    'GPSO',
    'OC',
    'OPLO',
    'OPSO',
    'TG',
    'XC',
  ],
};
