export default {
  id: null,
  name: '',
  shortName: '',
  numberOfConditions: -1,
  numberOfInstruments: -1,
  aggregatedCount: {
    instrument: [
      { name: '0', count: 0 },
      { name: '1', count: 0 },
      { name: '2', count: 0 },
      { name: '3', count: 0 },
      { name: '4', count: 0 },
      { name: '5', count: 0 },
      { name: '6', count: 0 },
      { name: '7', count: 0 },
      { name: '8', count: 0 },
      { name: 'OTHER', count: 0 },
    ],
    theme: [
      { name: 'ADMINISTRATIVE', count: 0 },
      { name: 'DAMAGE_PREVENTION', count: 0 },
      { name: 'EMERGENCY_MANAGEMENT', count: 0 },
      { name: 'ENFORCEMENT', count: 0 },
      { name: 'ENVIRONMENTAL_PROTECTION', count: 0 },
      { name: 'FINANCIAL', count: 0 },
      { name: 'INTEGRITY_MANAGEMENT', count: 0 },
      { name: 'MANAGEMENT_SYSTEM', count: 0 },
      { name: 'SAFETY_MANAGEMENT', count: 0 },
      { name: 'SECURITY', count: 0 },
      { name: 'SOCIO_ECONOMIC', count: 0 },
      { name: 'STANDARD_CONDITION', count: 0 },
      { name: 'SUNSET_CLAUSE', count: 0 },
    ],
    phase: [
      { name: 'ABANDONMENT', count: 0 },
      { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
      { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 6 },
      { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 0 },
      { name: 'NOT_CONSTRUCTION_RELATED', count: 33 },
      { name: 'POST_CONSTRUCTION_PHASE', count: 0 },
      { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
      { name: 'UNSPECIFIED', count: 0 },
    ],
    status: [
      { name: 'IN_PROGRESS', count: 0 },
      { name: 'CLOSED', count: 0 },
    ],
    type: [
      { name: 'NON_STANDARD', count: 0 },
      { name: 'STANDARD', count: 0 },
    ],
    filing: [
      { name: 'REQUIRED', count: 0 },
      { name: 'NOT_REQUIRED', count: 0 },
    ],
  },
};
