const locationData = [
  {
    id: 1,
    name: 'Prince Albert',
    province: 'SK',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 4 },
        { name: 'DAMAGE_PREVENTION', count: 2 },
        { name: 'EMERGENCY_MANAGEMENT', count: 2 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 7 },
        { name: 'FINANCIAL', count: 6 },
        { name: 'INTEGRITY_MANAGEMENT', count: 8 },
        { name: 'MANAGEMENT_SYSTEM', count: 2 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 1 },
        { name: 'STANDARD_CONDITION', count: 20 },
        { name: 'SUNSET_CLAUSE', count: 5 },
      ],
      status: [
        { name: 'CLOSED', count: 41 },
        { name: 'IN_PROGRESS', count: 9 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 30 },
        { name: 'STANDARD', count: 20 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 20 },
        { name: 'REQUIRED', count: 30 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 10 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 4 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 10 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 23 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 3 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 2,
    name: 'Camrose--Drumheller',
    province: 'AB',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 78 },
        { name: 'AO', count: 5 },
        { name: 'XO', count: 14 },
        { name: 'ZO', count: 145 },
        { name: 'OTHER', count: 162 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 78 },
        { name: 'DAMAGE_PREVENTION', count: 5 },
        { name: 'EMERGENCY_MANAGEMENT', count: 14 },
        { name: 'ENFORCEMENT', count: 145 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 162 },
        { name: 'FINANCIAL', count: 43 },
        { name: 'INTEGRITY_MANAGEMENT', count: 259 },
        { name: 'MANAGEMENT_SYSTEM', count: 14 },
        { name: 'SAFETY_MANAGEMENT', count: 19 },
        { name: 'SECURITY', count: 9 },
        { name: 'SOCIO_ECONOMIC', count: 65 },
        { name: 'STANDARD_CONDITION', count: 291 },
        { name: 'SUNSET_CLAUSE', count: 62 },
      ],
      status: [
        { name: 'CLOSED', count: 702 },
        { name: 'IN_PROGRESS', count: 162 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 571 },
        { name: 'STANDARD', count: 293 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 439 },
        { name: 'REQUIRED', count: 425 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 74 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 40 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 57 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 201 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 258 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 118 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 70 },
        { name: 'UNSPECIFIED', count: 46 },
      ],
    },
  },
  {
    id: 3,
    name: 'Northwest',
    province: 'ON',
    aggregatedCount: {
      instrument: [
        { name: 'GC', count: 13 },
        { name: 'OPL', count: 4 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 4 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 1 },
        { name: 'ENFORCEMENT', count: 13 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 4 },
        { name: 'FINANCIAL', count: 6 },
        { name: 'INTEGRITY_MANAGEMENT', count: 14 },
        { name: 'MANAGEMENT_SYSTEM', count: 5 },
        { name: 'SAFETY_MANAGEMENT', count: 2 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 1 },
        { name: 'STANDARD_CONDITION', count: 13 },
        { name: 'SUNSET_CLAUSE', count: 3 },
      ],
      status: [
        { name: 'CLOSED', count: 43 },
        { name: 'IN_PROGRESS', count: 2 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 32 },
        { name: 'STANDARD', count: 13 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 20 },
        { name: 'REQUIRED', count: 25 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 3 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 9 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 27 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 4 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 2 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 4,
    name: 'Lethbridge--Medicine Hat',
    province: 'AB',
    aggregatedCount: {
      instrument: [
        { name: 'XO', count: 7 },
        { name: 'MO', count: 12 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 29 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 9 },
        { name: 'ENFORCEMENT', count: 35 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 90 },
        { name: 'FINANCIAL', count: 31 },
        { name: 'INTEGRITY_MANAGEMENT', count: 101 },
        { name: 'MANAGEMENT_SYSTEM', count: 7 },
        { name: 'SAFETY_MANAGEMENT', count: 12 },
        { name: 'SECURITY', count: 2 },
        { name: 'SOCIO_ECONOMIC', count: 27 },
        { name: 'STANDARD_CONDITION', count: 114 },
        { name: 'SUNSET_CLAUSE', count: 22 },
      ],
      status: [
        { name: 'CLOSED', count: 334 },
        { name: 'IN_PROGRESS', count: 60 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 280 },
        { name: 'STANDARD', count: 114 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 159 },
        { name: 'REQUIRED', count: 235 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 48 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 20 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 21 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 69 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 85 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 57 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 68 },
        { name: 'UNSPECIFIED', count: 26 },
      ],
    },
  },
  {
    id: 5,
    name: 'Cape Breton',
    province: 'NS',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 2 },
        { name: 'AO', count: 3 },
        { name: 'SG', count: 0 },
        { name: 'ZO', count: 9 },
        { name: 'OTHER', count: 0 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 2 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 2 },
        { name: 'FINANCIAL', count: 3 },
        { name: 'INTEGRITY_MANAGEMENT', count: 0 },
        { name: 'MANAGEMENT_SYSTEM', count: 9 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 0 },
        { name: 'SUNSET_CLAUSE', count: 0 },
      ],
      status: [
        { name: 'CLOSED', count: 15 },
        { name: 'IN_PROGRESS', count: 0 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 15 },
        { name: 'STANDARD', count: 0 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 0 },
        { name: 'REQUIRED', count: 15 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 0 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 0 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 5 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 10 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 6,
    name: 'Montréal',
    province: 'QC',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 8 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 5 },
        { name: 'ENFORCEMENT', count: 27 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 5 },
        { name: 'FINANCIAL', count: 5 },
        { name: 'INTEGRITY_MANAGEMENT', count: 53 },
        { name: 'MANAGEMENT_SYSTEM', count: 4 },
        { name: 'SAFETY_MANAGEMENT', count: 2 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 16 },
        { name: 'SUNSET_CLAUSE', count: 3 },
      ],
      status: [
        { name: 'CLOSED', count: 74 },
        { name: 'IN_PROGRESS', count: 17 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 75 },
        { name: 'STANDARD', count: 16 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 31 },
        { name: 'REQUIRED', count: 60 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 3 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 12 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 61 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 6 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
        { name: 'UNSPECIFIED', count: 9 },
      ],
    },
  },
  {
    id: 7,
    name: 'London',
    province: 'ON',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 78 },
        { name: 'AO', count: 5 },
        { name: 'XO', count: 14 },
        { name: 'ZO', count: 145 },
        { name: 'OTHER', count: 162 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 6 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 2 },
        { name: 'ENFORCEMENT', count: 15 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 1 },
        { name: 'FINANCIAL', count: 0 },
        { name: 'INTEGRITY_MANAGEMENT', count: 8 },
        { name: 'MANAGEMENT_SYSTEM', count: 4 },
        { name: 'SAFETY_MANAGEMENT', count: 2 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 4 },
        { name: 'SUNSET_CLAUSE', count: 1 },
      ],
      status: [
        { name: 'CLOSED', count: 24 },
        { name: 'IN_PROGRESS', count: 0 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 20 },
        { name: 'STANDARD', count: 4 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 5 },
        { name: 'REQUIRED', count: 19 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 1 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 3 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 14 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 3 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 2 },
        { name: 'UNSPECIFIED', count: 1 },
      ],
    },
  },
  {
    id: 8,
    name: 'Outaouais',
    province: 'QC',
    aggregatedCount: {
      instrument: [
        { name: 'GC', count: 13 },
        { name: 'OPL', count: 4 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 2 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 0 },
        { name: 'FINANCIAL', count: 4 },
        { name: 'INTEGRITY_MANAGEMENT', count: 0 },
        { name: 'MANAGEMENT_SYSTEM', count: 2 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 13 },
        { name: 'SUNSET_CLAUSE', count: 2 },
      ],
      status: [
        { name: 'CLOSED', count: 22 },
        { name: 'IN_PROGRESS', count: 1 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 9 },
        { name: 'STANDARD', count: 14 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 5 },
        { name: 'REQUIRED', count: 18 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 2 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 0 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 8 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 0 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
        { name: 'UNSPECIFIED', count: 13 },
      ],
    },
  },
  {
    id: 9,
    name: 'Moncton--Richibucto',
    province: 'NB',
    aggregatedCount: {
      instrument: [
        { name: 'XO', count: 7 },
        { name: 'MO', count: 12 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 1 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 1 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 3 },
        { name: 'FINANCIAL', count: 2 },
        { name: 'INTEGRITY_MANAGEMENT', count: 3 },
        { name: 'MANAGEMENT_SYSTEM', count: 9 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 4 },
        { name: 'SUNSET_CLAUSE', count: 1 },
      ],
      status: [
        { name: 'CLOSED', count: 21 },
        { name: 'IN_PROGRESS', count: 0 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 17 },
        { name: 'STANDARD', count: 4 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 4 },
        { name: 'REQUIRED', count: 17 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 2 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 1 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 3 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 3 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 11 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 1 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 11,
    name: 'Halifax',
    province: 'NS',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 2 },
        { name: 'AO', count: 3 },
        { name: 'SG', count: 0 },
        { name: 'ZO', count: 9 },
        { name: 'OTHER', count: 0 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 1 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 2 },
        { name: 'FINANCIAL', count: 2 },
        { name: 'INTEGRITY_MANAGEMENT', count: 0 },
        { name: 'MANAGEMENT_SYSTEM', count: 9 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 0 },
        { name: 'SUNSET_CLAUSE', count: 0 },
      ],
      status: [
        { name: 'CLOSED', count: 13 },
        { name: 'IN_PROGRESS', count: 0 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 13 },
        { name: 'STANDARD', count: 0 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 0 },
        { name: 'REQUIRED', count: 13 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 0 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 0 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 3 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 10 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 12,
    name: 'South Central',
    province: 'MB',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 30 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 6 },
        { name: 'ENFORCEMENT', count: 25 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 45 },
        { name: 'FINANCIAL', count: 4 },
        { name: 'INTEGRITY_MANAGEMENT', count: 47 },
        { name: 'MANAGEMENT_SYSTEM', count: 4 },
        { name: 'SAFETY_MANAGEMENT', count: 5 },
        { name: 'SECURITY', count: 5 },
        { name: 'SOCIO_ECONOMIC', count: 39 },
        { name: 'STANDARD_CONDITION', count: 54 },
        { name: 'SUNSET_CLAUSE', count: 13 },
      ],
      status: [
        { name: 'CLOSED', count: 151 },
        { name: 'IN_PROGRESS', count: 63 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 160 },
        { name: 'STANDARD', count: 54 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 79 },
        { name: 'REQUIRED', count: 135 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 29 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 13 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 42 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 33 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 42 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 37 },
        { name: 'UNSPECIFIED', count: 18 },
      ],
    },
  },
  {
    id: 13,
    name: 'Abitibi-Témiscamingue',
    province: 'QC',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 78 },
        { name: 'AO', count: 5 },
        { name: 'XO', count: 14 },
        { name: 'ZO', count: 145 },
        { name: 'OTHER', count: 162 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 1 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 1 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 2 },
        { name: 'FINANCIAL', count: 2 },
        { name: 'INTEGRITY_MANAGEMENT', count: 2 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 1 },
        { name: 'SECURITY', count: 1 },
        { name: 'SOCIO_ECONOMIC', count: 1 },
        { name: 'STANDARD_CONDITION', count: 8 },
        { name: 'SUNSET_CLAUSE', count: 2 },
      ],
      status: [
        { name: 'CLOSED', count: 17 },
        { name: 'IN_PROGRESS', count: 0 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 9 },
        { name: 'STANDARD', count: 8 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 8 },
        { name: 'REQUIRED', count: 9 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 2 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 6 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 3 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 2 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 4 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 14,
    name: 'Banff--Jasper--Rocky Mountain House',
    province: 'AB',
    aggregatedCount: {
      instrument: [
        { name: 'GC', count: 13 },
        { name: 'OPL', count: 4 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 53 },
        { name: 'DAMAGE_PREVENTION', count: 2 },
        { name: 'EMERGENCY_MANAGEMENT', count: 41 },
        { name: 'ENFORCEMENT', count: 29 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 267 },
        { name: 'FINANCIAL', count: 16 },
        { name: 'INTEGRITY_MANAGEMENT', count: 197 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 9 },
        { name: 'SECURITY', count: 8 },
        { name: 'SOCIO_ECONOMIC', count: 100 },
        { name: 'STANDARD_CONDITION', count: 198 },
        { name: 'SUNSET_CLAUSE', count: 42 },
      ],
      status: [
        { name: 'CLOSED', count: 478 },
        { name: 'IN_PROGRESS', count: 350 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 623 },
        { name: 'STANDARD', count: 205 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 236 },
        { name: 'REQUIRED', count: 592 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 3 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 90 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 46 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 215 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 53 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 142 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 261 },
        { name: 'UNSPECIFIED', count: 18 },
      ],
    },
  },
  {
    id: 15,
    name: 'Laval',
    province: 'QC',
    aggregatedCount: {
      instrument: [
        { name: 'XO', count: 7 },
        { name: 'MO', count: 12 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 1 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 3 },
        { name: 'ENFORCEMENT', count: 11 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 1 },
        { name: 'FINANCIAL', count: 3 },
        { name: 'INTEGRITY_MANAGEMENT', count: 43 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 0 },
        { name: 'SUNSET_CLAUSE', count: 0 },
      ],
      status: [
        { name: 'CLOSED', count: 34 },
        { name: 'IN_PROGRESS', count: 17 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 51 },
        { name: 'STANDARD', count: 0 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 15 },
        { name: 'REQUIRED', count: 36 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 0 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 0 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 43 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 0 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
        { name: 'UNSPECIFIED', count: 8 },
      ],
    },
  },
  {
    id: 16,
    name: 'North Central',
    province: 'MB',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 2 },
        { name: 'AO', count: 3 },
        { name: 'SG', count: 0 },
        { name: 'ZO', count: 9 },
        { name: 'OTHER', count: 0 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 7 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 7 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 1 },
        { name: 'FINANCIAL', count: 8 },
        { name: 'INTEGRITY_MANAGEMENT', count: 4 },
        { name: 'MANAGEMENT_SYSTEM', count: 6 },
        { name: 'SAFETY_MANAGEMENT', count: 1 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 10 },
        { name: 'SUNSET_CLAUSE', count: 1 },
      ],
      status: [
        { name: 'CLOSED', count: 30 },
        { name: 'IN_PROGRESS', count: 3 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 23 },
        { name: 'STANDARD', count: 10 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 7 },
        { name: 'REQUIRED', count: 26 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 1 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 3 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 23 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 1 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
        { name: 'UNSPECIFIED', count: 5 },
      ],
    },
  },
  {
    id: 17,
    name: 'Muskoka--Kawarthas',
    province: 'ON',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 12 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 7 },
        { name: 'ENFORCEMENT', count: 16 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 5 },
        { name: 'FINANCIAL', count: 2 },
        { name: 'INTEGRITY_MANAGEMENT', count: 17 },
        { name: 'MANAGEMENT_SYSTEM', count: 4 },
        { name: 'SAFETY_MANAGEMENT', count: 2 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 3 },
        { name: 'STANDARD_CONDITION', count: 4 },
        { name: 'SUNSET_CLAUSE', count: 1 },
      ],
      status: [
        { name: 'CLOSED', count: 45 },
        { name: 'IN_PROGRESS', count: 6 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 47 },
        { name: 'STANDARD', count: 4 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 6 },
        { name: 'REQUIRED', count: 45 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 1 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 5 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 18 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 23 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 3 },
        { name: 'UNSPECIFIED', count: 1 },
      ],
    },
  },
  {
    id: 18,
    name: 'Regina--Moose Mountain',
    province: 'SK',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 78 },
        { name: 'AO', count: 5 },
        { name: 'XO', count: 14 },
        { name: 'ZO', count: 145 },
        { name: 'OTHER', count: 162 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 65 },
        { name: 'DAMAGE_PREVENTION', count: 45 },
        { name: 'EMERGENCY_MANAGEMENT', count: 58 },
        { name: 'ENFORCEMENT', count: 53 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 129 },
        { name: 'FINANCIAL', count: 35 },
        { name: 'INTEGRITY_MANAGEMENT', count: 239 },
        { name: 'MANAGEMENT_SYSTEM', count: 12 },
        { name: 'SAFETY_MANAGEMENT', count: 21 },
        { name: 'SECURITY', count: 9 },
        { name: 'SOCIO_ECONOMIC', count: 55 },
        { name: 'STANDARD_CONDITION', count: 308 },
        { name: 'SUNSET_CLAUSE', count: 49 },
      ],
      status: [
        { name: 'CLOSED', count: 787 },
        { name: 'IN_PROGRESS', count: 115 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 594 },
        { name: 'STANDARD', count: 308 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 318 },
        { name: 'REQUIRED', count: 584 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 60 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 55 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 168 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 366 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 120 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 109 },
        { name: 'UNSPECIFIED', count: 24 },
      ],
    },
  },
  {
    id: 19,
    name: 'Capitale-Nationale',
    province: 'QC',
    aggregatedCount: {
      instrument: [
        { name: 'GC', count: 13 },
        { name: 'OPL', count: 4 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 2 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 5 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 0 },
        { name: 'FINANCIAL', count: 2 },
        { name: 'INTEGRITY_MANAGEMENT', count: 17 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 0 },
        { name: 'SUNSET_CLAUSE', count: 0 },
      ],
      status: [
        { name: 'CLOSED', count: 18 },
        { name: 'IN_PROGRESS', count: 3 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 21 },
        { name: 'STANDARD', count: 0 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 2 },
        { name: 'REQUIRED', count: 19 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 1 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 0 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 1 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 6 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 3 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 1 },
        { name: 'UNSPECIFIED', count: 9 },
      ],
    },
  },
  {
    id: 20,
    name: 'Calgary',
    province: 'AB',
    aggregatedCount: {
      instrument: [
        { name: 'XO', count: 7 },
        { name: 'MO', count: 12 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 27 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 1 },
        { name: 'ENFORCEMENT', count: 113 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 12 },
        { name: 'FINANCIAL', count: 5 },
        { name: 'INTEGRITY_MANAGEMENT', count: 140 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 6 },
        { name: 'SECURITY', count: 1 },
        { name: 'SOCIO_ECONOMIC', count: 4 },
        { name: 'STANDARD_CONDITION', count: 39 },
        { name: 'SUNSET_CLAUSE', count: 5 },
      ],
      status: [
        { name: 'CLOSED', count: 195 },
        { name: 'IN_PROGRESS', count: 30 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 186 },
        { name: 'STANDARD', count: 39 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 160 },
        { name: 'REQUIRED', count: 65 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 7 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 6 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 27 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 136 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 12 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 8 },
        { name: 'UNSPECIFIED', count: 29 },
      ],
    },
  },
  {
    id: 21,
    name: 'Saskatoon--Biggar',
    province: 'SK',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 2 },
        { name: 'AO', count: 3 },
        { name: 'SG', count: 0 },
        { name: 'ZO', count: 9 },
        { name: 'OTHER', count: 0 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 20 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 4 },
        { name: 'ENFORCEMENT', count: 37 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 44 },
        { name: 'FINANCIAL', count: 13 },
        { name: 'INTEGRITY_MANAGEMENT', count: 55 },
        { name: 'MANAGEMENT_SYSTEM', count: 7 },
        { name: 'SAFETY_MANAGEMENT', count: 5 },
        { name: 'SECURITY', count: 2 },
        { name: 'SOCIO_ECONOMIC', count: 12 },
        { name: 'STANDARD_CONDITION', count: 86 },
        { name: 'SUNSET_CLAUSE', count: 20 },
      ],
      status: [
        { name: 'CLOSED', count: 190 },
        { name: 'IN_PROGRESS', count: 31 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 134 },
        { name: 'STANDARD', count: 87 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 96 },
        { name: 'REQUIRED', count: 125 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 16 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 13 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 19 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 58 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 57 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 40 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 16 },
        { name: 'UNSPECIFIED', count: 2 },
      ],
    },
  },
  {
    id: 22,
    name: 'Mauricie',
    province: 'QC',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 2 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 5 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 0 },
        { name: 'FINANCIAL', count: 2 },
        { name: 'INTEGRITY_MANAGEMENT', count: 17 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 0 },
        { name: 'SUNSET_CLAUSE', count: 0 },
      ],
      status: [
        { name: 'CLOSED', count: 18 },
        { name: 'IN_PROGRESS', count: 3 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 21 },
        { name: 'STANDARD', count: 0 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 2 },
        { name: 'REQUIRED', count: 19 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 1 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 0 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 1 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 6 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 3 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 1 },
        { name: 'UNSPECIFIED', count: 9 },
      ],
    },
  },
  {
    id: 23,
    name: 'Southeast',
    province: 'MB',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 78 },
        { name: 'AO', count: 5 },
        { name: 'XO', count: 14 },
        { name: 'ZO', count: 145 },
        { name: 'OTHER', count: 162 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 4 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 1 },
        { name: 'ENFORCEMENT', count: 1 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 2 },
        { name: 'FINANCIAL', count: 4 },
        { name: 'INTEGRITY_MANAGEMENT', count: 4 },
        { name: 'MANAGEMENT_SYSTEM', count: 5 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 9 },
        { name: 'SUNSET_CLAUSE', count: 2 },
      ],
      status: [
        { name: 'CLOSED', count: 25 },
        { name: 'IN_PROGRESS', count: 0 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 16 },
        { name: 'STANDARD', count: 9 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 10 },
        { name: 'REQUIRED', count: 15 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 2 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 6 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 13 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 4 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 24,
    name: 'Estrie',
    province: 'QC',
    aggregatedCount: {
      instrument: [
        { name: 'GC', count: 13 },
        { name: 'OPL', count: 4 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 3 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 4 },
        { name: 'FINANCIAL', count: 2 },
        { name: 'INTEGRITY_MANAGEMENT', count: 12 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 16 },
        { name: 'SUNSET_CLAUSE', count: 4 },
      ],
      status: [
        { name: 'CLOSED', count: 26 },
        { name: 'IN_PROGRESS', count: 7 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 15 },
        { name: 'STANDARD', count: 18 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 16 },
        { name: 'REQUIRED', count: 17 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 4 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 12 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 4 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 9 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 4 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 25,
    name: 'Toronto',
    province: 'ON',
    aggregatedCount: {
      instrument: [
        { name: 'XO', count: 7 },
        { name: 'MO', count: 12 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 21 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 12 },
        { name: 'ENFORCEMENT', count: 27 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 41 },
        { name: 'FINANCIAL', count: 8 },
        { name: 'INTEGRITY_MANAGEMENT', count: 103 },
        { name: 'MANAGEMENT_SYSTEM', count: 4 },
        { name: 'SAFETY_MANAGEMENT', count: 6 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 23 },
        { name: 'STANDARD_CONDITION', count: 64 },
        { name: 'SUNSET_CLAUSE', count: 15 },
      ],
      status: [
        { name: 'CLOSED', count: 229 },
        { name: 'IN_PROGRESS', count: 37 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 200 },
        { name: 'STANDARD', count: 66 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 94 },
        { name: 'REQUIRED', count: 172 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 12 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 15 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 53 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 73 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 63 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 37 },
        { name: 'UNSPECIFIED', count: 13 },
      ],
    },
  },
  {
    id: 26,
    name: 'Northwest Territories',
    province: 'NT',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 2 },
        { name: 'AO', count: 3 },
        { name: 'SG', count: 0 },
        { name: 'ZO', count: 9 },
        { name: 'OTHER', count: 0 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 22 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 4 },
        { name: 'ENFORCEMENT', count: 12 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 45 },
        { name: 'FINANCIAL', count: 27 },
        { name: 'INTEGRITY_MANAGEMENT', count: 56 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 7 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 13 },
        { name: 'STANDARD_CONDITION', count: 23 },
        { name: 'SUNSET_CLAUSE', count: 4 },
      ],
      status: [
        { name: 'CLOSED', count: 74 },
        { name: 'IN_PROGRESS', count: 94 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 145 },
        { name: 'STANDARD', count: 23 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 51 },
        { name: 'REQUIRED', count: 117 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 17 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 4 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 26 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 33 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 21 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 57 },
        { name: 'UNSPECIFIED', count: 10 },
      ],
    },
  },
  {
    id: 27,
    name: 'Fredericton--Oromocto',
    province: 'NB',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 1 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 2 },
        { name: 'FINANCIAL', count: 2 },
        { name: 'INTEGRITY_MANAGEMENT', count: 0 },
        { name: 'MANAGEMENT_SYSTEM', count: 9 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 2 },
        { name: 'SUNSET_CLAUSE', count: 1 },
      ],
      status: [
        { name: 'CLOSED', count: 16 },
        { name: 'IN_PROGRESS', count: 0 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 14 },
        { name: 'STANDARD', count: 2 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 2 },
        { name: 'REQUIRED', count: 14 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 1 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 2 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 3 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 10 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 28,
    name: 'Lanaudière',
    province: 'QC',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 78 },
        { name: 'AO', count: 5 },
        { name: 'XO', count: 14 },
        { name: 'ZO', count: 145 },
        { name: 'OTHER', count: 162 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 14 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 7 },
        { name: 'ENFORCEMENT', count: 20 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 7 },
        { name: 'FINANCIAL', count: 4 },
        { name: 'INTEGRITY_MANAGEMENT', count: 47 },
        { name: 'MANAGEMENT_SYSTEM', count: 4 },
        { name: 'SAFETY_MANAGEMENT', count: 3 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 3 },
        { name: 'STANDARD_CONDITION', count: 12 },
        { name: 'SUNSET_CLAUSE', count: 3 },
      ],
      status: [
        { name: 'CLOSED', count: 85 },
        { name: 'IN_PROGRESS', count: 11 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 84 },
        { name: 'STANDARD', count: 12 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 28 },
        { name: 'REQUIRED', count: 68 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 1 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 3 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 12 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 30 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 33 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 4 },
        { name: 'UNSPECIFIED', count: 13 },
      ],
    },
  },
  {
    id: 29,
    name: 'Swift Current--Moose Jaw',
    province: 'SK',
    aggregatedCount: {
      instrument: [
        { name: 'GC', count: 13 },
        { name: 'OPL', count: 4 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 23 },
        { name: 'DAMAGE_PREVENTION', count: 1 },
        { name: 'EMERGENCY_MANAGEMENT', count: 11 },
        { name: 'ENFORCEMENT', count: 19 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 60 },
        { name: 'FINANCIAL', count: 14 },
        { name: 'INTEGRITY_MANAGEMENT', count: 65 },
        { name: 'MANAGEMENT_SYSTEM', count: 7 },
        { name: 'SAFETY_MANAGEMENT', count: 6 },
        { name: 'SECURITY', count: 1 },
        { name: 'SOCIO_ECONOMIC', count: 24 },
        { name: 'STANDARD_CONDITION', count: 77 },
        { name: 'SUNSET_CLAUSE', count: 15 },
      ],
      status: [
        { name: 'CLOSED', count: 226 },
        { name: 'IN_PROGRESS', count: 42 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 189 },
        { name: 'STANDARD', count: 79 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 95 },
        { name: 'REQUIRED', count: 173 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 10 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 18 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 17 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 59 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 44 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 47 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 60 },
        { name: 'UNSPECIFIED', count: 13 },
      ],
    },
  },
  {
    id: 30,
    name: 'Red Deer',
    province: 'AB',
    aggregatedCount: {
      instrument: [
        { name: 'XO', count: 7 },
        { name: 'MO', count: 12 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 1 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 24 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 1 },
        { name: 'FINANCIAL', count: 3 },
        { name: 'INTEGRITY_MANAGEMENT', count: 37 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 5 },
        { name: 'SUNSET_CLAUSE', count: 2 },
      ],
      status: [
        { name: 'CLOSED', count: 38 },
        { name: 'IN_PROGRESS', count: 9 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 42 },
        { name: 'STANDARD', count: 5 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 29 },
        { name: 'REQUIRED', count: 18 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 2 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 3 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 28 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 1 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 1 },
        { name: 'UNSPECIFIED', count: 12 },
      ],
    },
  },
  {
    id: 31,
    name: 'Nechako',
    province: 'BC',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 2 },
        { name: 'AO', count: 3 },
        { name: 'SG', count: 0 },
        { name: 'ZO', count: 9 },
        { name: 'OTHER', count: 0 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 1 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 0 },
        { name: 'FINANCIAL', count: 2 },
        { name: 'INTEGRITY_MANAGEMENT', count: 0 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 0 },
        { name: 'SUNSET_CLAUSE', count: 0 },
      ],
      status: [
        { name: 'CLOSED', count: 3 },
        { name: 'IN_PROGRESS', count: 0 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 3 },
        { name: 'STANDARD', count: 0 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 0 },
        { name: 'REQUIRED', count: 3 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 0 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 0 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 3 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 0 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 32,
    name: 'Edmonton',
    province: 'AB',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 25 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 11 },
        { name: 'ENFORCEMENT', count: 36 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 69 },
        { name: 'FINANCIAL', count: 17 },
        { name: 'INTEGRITY_MANAGEMENT', count: 89 },
        { name: 'MANAGEMENT_SYSTEM', count: 7 },
        { name: 'SAFETY_MANAGEMENT', count: 9 },
        { name: 'SECURITY', count: 3 },
        { name: 'SOCIO_ECONOMIC', count: 17 },
        { name: 'STANDARD_CONDITION', count: 221 },
        { name: 'SUNSET_CLAUSE', count: 59 },
      ],
      status: [
        { name: 'CLOSED', count: 374 },
        { name: 'IN_PROGRESS', count: 42 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 192 },
        { name: 'STANDARD', count: 224 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 250 },
        { name: 'REQUIRED', count: 166 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 10 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 58 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 176 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 55 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 83 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 15 },
        { name: 'UNSPECIFIED', count: 19 },
      ],
    },
  },
  {
    id: 33,
    name: 'Saint John--St. Stephen',
    province: 'NB',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 1 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 2 },
        { name: 'FINANCIAL', count: 2 },
        { name: 'INTEGRITY_MANAGEMENT', count: 0 },
        { name: 'MANAGEMENT_SYSTEM', count: 13 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 0 },
        { name: 'SUNSET_CLAUSE', count: 0 },
      ],
      status: [
        { name: 'CLOSED', count: 17 },
        { name: 'IN_PROGRESS', count: 0 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 17 },
        { name: 'STANDARD', count: 0 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 3 },
        { name: 'REQUIRED', count: 14 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 0 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 0 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 7 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 10 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 34,
    name: 'Hamilton--Niagara Peninsula',
    province: 'ON',
    aggregatedCount: {
      instrument: [
        { name: 'GC', count: 13 },
        { name: 'OPL', count: 4 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 27 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 13 },
        { name: 'ENFORCEMENT', count: 27 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 31 },
        { name: 'FINANCIAL', count: 9 },
        { name: 'INTEGRITY_MANAGEMENT', count: 115 },
        { name: 'MANAGEMENT_SYSTEM', count: 4 },
        { name: 'SAFETY_MANAGEMENT', count: 5 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 14 },
        { name: 'STANDARD_CONDITION', count: 51 },
        { name: 'SUNSET_CLAUSE', count: 15 },
      ],
      status: [
        { name: 'CLOSED', count: 209 },
        { name: 'IN_PROGRESS', count: 46 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 202 },
        { name: 'STANDARD', count: 53 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 87 },
        { name: 'REQUIRED', count: 168 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 7 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 12 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 15 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 46 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 72 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 60 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 30 },
        { name: 'UNSPECIFIED', count: 13 },
      ],
    },
  },
  {
    id: 35,
    name: 'Yorkton--Melville',
    province: 'SK',
    aggregatedCount: {
      instrument: [
        { name: 'XO', count: 7 },
        { name: 'MO', count: 12 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 15 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 2 },
        { name: 'ENFORCEMENT', count: 22 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 16 },
        { name: 'FINANCIAL', count: 6 },
        { name: 'INTEGRITY_MANAGEMENT', count: 18 },
        { name: 'MANAGEMENT_SYSTEM', count: 10 },
        { name: 'SAFETY_MANAGEMENT', count: 4 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 1 },
        { name: 'STANDARD_CONDITION', count: 34 },
        { name: 'SUNSET_CLAUSE', count: 9 },
      ],
      status: [
        { name: 'CLOSED', count: 90 },
        { name: 'IN_PROGRESS', count: 3 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 59 },
        { name: 'STANDARD', count: 34 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 38 },
        { name: 'REQUIRED', count: 55 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 3 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 9 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 24 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 34 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 14 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 7 },
        { name: 'UNSPECIFIED', count: 2 },
      ],
    },
  },
  {
    id: 36,
    name: 'Windsor--Sarnia',
    province: 'ON',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 2 },
        { name: 'AO', count: 3 },
        { name: 'SG', count: 0 },
        { name: 'ZO', count: 9 },
        { name: 'OTHER', count: 0 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 23 },
        { name: 'DAMAGE_PREVENTION', count: 2 },
        { name: 'EMERGENCY_MANAGEMENT', count: 10 },
        { name: 'ENFORCEMENT', count: 21 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 31 },
        { name: 'FINANCIAL', count: 23 },
        { name: 'INTEGRITY_MANAGEMENT', count: 66 },
        { name: 'MANAGEMENT_SYSTEM', count: 7 },
        { name: 'SAFETY_MANAGEMENT', count: 5 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 7 },
        { name: 'STANDARD_CONDITION', count: 101 },
        { name: 'SUNSET_CLAUSE', count: 20 },
      ],
      status: [
        { name: 'CLOSED', count: 237 },
        { name: 'IN_PROGRESS', count: 17 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 149 },
        { name: 'STANDARD', count: 105 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 110 },
        { name: 'REQUIRED', count: 144 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 8 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 20 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 76 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 72 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 51 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 16 },
        { name: 'UNSPECIFIED', count: 11 },
      ],
    },
  },
  {
    id: 37,
    name: 'Athabasca--Grande Prairie--Peace River',
    province: 'AB',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 74 },
        { name: 'DAMAGE_PREVENTION', count: 8 },
        { name: 'EMERGENCY_MANAGEMENT', count: 24 },
        { name: 'ENFORCEMENT', count: 51 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 343 },
        { name: 'FINANCIAL', count: 48 },
        { name: 'INTEGRITY_MANAGEMENT', count: 327 },
        { name: 'MANAGEMENT_SYSTEM', count: 6 },
        { name: 'SAFETY_MANAGEMENT', count: 23 },
        { name: 'SECURITY', count: 4 },
        { name: 'SOCIO_ECONOMIC', count: 98 },
        { name: 'STANDARD_CONDITION', count: 619 },
        { name: 'SUNSET_CLAUSE', count: 114 },
      ],
      status: [
        { name: 'CLOSED', count: 1210 },
        { name: 'IN_PROGRESS', count: 213 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 772 },
        { name: 'STANDARD', count: 651 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 637 },
        { name: 'REQUIRED', count: 786 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 65 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 100 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 121 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 390 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 229 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 261 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 219 },
        { name: 'UNSPECIFIED', count: 38 },
      ],
    },
  },
  {
    id: 38,
    name: 'Ottawa',
    province: 'ON',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 15 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 11 },
        { name: 'ENFORCEMENT', count: 27 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 16 },
        { name: 'FINANCIAL', count: 16 },
        { name: 'INTEGRITY_MANAGEMENT', count: 63 },
        { name: 'MANAGEMENT_SYSTEM', count: 6 },
        { name: 'SAFETY_MANAGEMENT', count: 4 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 10 },
        { name: 'STANDARD_CONDITION', count: 38 },
        { name: 'SUNSET_CLAUSE', count: 8 },
      ],
      status: [
        { name: 'CLOSED', count: 143 },
        { name: 'IN_PROGRESS', count: 27 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 132 },
        { name: 'STANDARD', count: 38 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 50 },
        { name: 'REQUIRED', count: 120 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 1 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 8 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 20 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 71 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 35 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 13 },
        { name: 'UNSPECIFIED', count: 22 },
      ],
    },
  },
  {
    id: 39,
    name: 'Kingston--Pembroke',
    province: 'ON',
    aggregatedCount: {
      instrument: [
        { name: 'GC', count: 13 },
        { name: 'OPL', count: 4 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 13 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 10 },
        { name: 'ENFORCEMENT', count: 25 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 7 },
        { name: 'FINANCIAL', count: 7 },
        { name: 'INTEGRITY_MANAGEMENT', count: 72 },
        { name: 'MANAGEMENT_SYSTEM', count: 4 },
        { name: 'SAFETY_MANAGEMENT', count: 3 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 3 },
        { name: 'STANDARD_CONDITION', count: 8 },
        { name: 'SUNSET_CLAUSE', count: 2 },
      ],
      status: [
        { name: 'CLOSED', count: 98 },
        { name: 'IN_PROGRESS', count: 25 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 115 },
        { name: 'STANDARD', count: 8 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 37 },
        { name: 'REQUIRED', count: 86 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 2 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 8 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 71 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 27 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 3 },
        { name: 'UNSPECIFIED', count: 12 },
      ],
    },
  },
  {
    id: 40,
    name: 'Montérégie',
    province: 'QC',
    aggregatedCount: {
      instrument: [
        { name: 'XO', count: 7 },
        { name: 'MO', count: 12 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 4 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 3 },
        { name: 'ENFORCEMENT', count: 12 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 6 },
        { name: 'FINANCIAL', count: 7 },
        { name: 'INTEGRITY_MANAGEMENT', count: 44 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 1 },
        { name: 'STANDARD_CONDITION', count: 20 },
        { name: 'SUNSET_CLAUSE', count: 5 },
      ],
      status: [
        { name: 'CLOSED', count: 65 },
        { name: 'IN_PROGRESS', count: 15 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 59 },
        { name: 'STANDARD', count: 21 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 34 },
        { name: 'REQUIRED', count: 46 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 5 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 15 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 46 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 5 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 1 },
        { name: 'UNSPECIFIED', count: 8 },
      ],
    },
  },
  {
    id: 41,
    name: 'Northeast',
    province: 'BC',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 2 },
        { name: 'AO', count: 3 },
        { name: 'SG', count: 0 },
        { name: 'ZO', count: 9 },
        { name: 'OTHER', count: 0 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 76 },
        { name: 'DAMAGE_PREVENTION', count: 5 },
        { name: 'EMERGENCY_MANAGEMENT', count: 28 },
        { name: 'ENFORCEMENT', count: 7 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 284 },
        { name: 'FINANCIAL', count: 50 },
        { name: 'INTEGRITY_MANAGEMENT', count: 198 },
        { name: 'MANAGEMENT_SYSTEM', count: 3 },
        { name: 'SAFETY_MANAGEMENT', count: 29 },
        { name: 'SECURITY', count: 6 },
        { name: 'SOCIO_ECONOMIC', count: 84 },
        { name: 'STANDARD_CONDITION', count: 488 },
        { name: 'SUNSET_CLAUSE', count: 83 },
      ],
      status: [
        { name: 'CLOSED', count: 965 },
        { name: 'IN_PROGRESS', count: 173 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 636 },
        { name: 'STANDARD', count: 502 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 460 },
        { name: 'REQUIRED', count: 678 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 34 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 99 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 80 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 343 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 175 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 213 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 175 },
        { name: 'UNSPECIFIED', count: 19 },
      ],
    },
  },
  {
    id: 42,
    name: 'Wood Buffalo--Cold Lake',
    province: 'AB',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 15 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 2 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 88 },
        { name: 'FINANCIAL', count: 4 },
        { name: 'INTEGRITY_MANAGEMENT', count: 49 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 7 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 26 },
        { name: 'STANDARD_CONDITION', count: 120 },
        { name: 'SUNSET_CLAUSE', count: 30 },
      ],
      status: [
        { name: 'CLOSED', count: 235 },
        { name: 'IN_PROGRESS', count: 44 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 159 },
        { name: 'STANDARD', count: 120 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 126 },
        { name: 'REQUIRED', count: 153 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 23 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 26 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 29 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 90 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 5 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 58 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 45 },
        { name: 'UNSPECIFIED', count: 3 },
      ],
    },
  },
  {
    id: 43,
    name: 'Southwest',
    province: 'MB',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 28 },
        { name: 'DAMAGE_PREVENTION', count: 6 },
        { name: 'EMERGENCY_MANAGEMENT', count: 8 },
        { name: 'ENFORCEMENT', count: 32 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 40 },
        { name: 'FINANCIAL', count: 12 },
        { name: 'INTEGRITY_MANAGEMENT', count: 59 },
        { name: 'MANAGEMENT_SYSTEM', count: 10 },
        { name: 'SAFETY_MANAGEMENT', count: 4 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 14 },
        { name: 'STANDARD_CONDITION', count: 113 },
        { name: 'SUNSET_CLAUSE', count: 24 },
      ],
      status: [
        { name: 'CLOSED', count: 250 },
        { name: 'IN_PROGRESS', count: 15 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 150 },
        { name: 'STANDARD', count: 115 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 129 },
        { name: 'REQUIRED', count: 136 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 6 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 24 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 77 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 89 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 36 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 14 },
        { name: 'UNSPECIFIED', count: 19 },
      ],
    },
  },
  {
    id: 44,
    name: 'Laurentides',
    province: 'QC',
    aggregatedCount: {
      instrument: [
        { name: 'GC', count: 13 },
        { name: 'OPL', count: 4 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 14 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 10 },
        { name: 'ENFORCEMENT', count: 29 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 8 },
        { name: 'FINANCIAL', count: 7 },
        { name: 'INTEGRITY_MANAGEMENT', count: 85 },
        { name: 'MANAGEMENT_SYSTEM', count: 4 },
        { name: 'SAFETY_MANAGEMENT', count: 3 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 3 },
        { name: 'STANDARD_CONDITION', count: 12 },
        { name: 'SUNSET_CLAUSE', count: 3 },
      ],
      status: [
        { name: 'CLOSED', count: 109 },
        { name: 'IN_PROGRESS', count: 32 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 128 },
        { name: 'STANDARD', count: 13 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 42 },
        { name: 'REQUIRED', count: 99 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 2 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 6 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 9 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 68 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 31 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 4 },
        { name: 'UNSPECIFIED', count: 21 },
      ],
    },
  },
  {
    id: 45,
    name: 'Cariboo',
    province: 'BC',
    aggregatedCount: {
      instrument: [
        { name: 'XO', count: 7 },
        { name: 'MO', count: 12 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 41 },
        { name: 'DAMAGE_PREVENTION', count: 2 },
        { name: 'EMERGENCY_MANAGEMENT', count: 39 },
        { name: 'ENFORCEMENT', count: 5 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 204 },
        { name: 'FINANCIAL', count: 11 },
        { name: 'INTEGRITY_MANAGEMENT', count: 112 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 9 },
        { name: 'SECURITY', count: 7 },
        { name: 'SOCIO_ECONOMIC', count: 74 },
        { name: 'STANDARD_CONDITION', count: 64 },
        { name: 'SUNSET_CLAUSE', count: 14 },
      ],
      status: [
        { name: 'CLOSED', count: 244 },
        { name: 'IN_PROGRESS', count: 294 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 475 },
        { name: 'STANDARD', count: 63 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 78 },
        { name: 'REQUIRED', count: 460 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 76 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 14 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 117 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 17 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 83 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 223 },
        { name: 'UNSPECIFIED', count: 8 },
      ],
    },
  },
  {
    id: 47,
    name: 'Thompson--Okanagan',
    province: 'BC',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 2 },
        { name: 'AO', count: 3 },
        { name: 'SG', count: 0 },
        { name: 'ZO', count: 9 },
        { name: 'OTHER', count: 0 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 10 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 3 },
        { name: 'ENFORCEMENT', count: 5 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 40 },
        { name: 'FINANCIAL', count: 6 },
        { name: 'INTEGRITY_MANAGEMENT', count: 30 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 3 },
        { name: 'SECURITY', count: 2 },
        { name: 'SOCIO_ECONOMIC', count: 12 },
        { name: 'STANDARD_CONDITION', count: 40 },
        { name: 'SUNSET_CLAUSE', count: 8 },
      ],
      status: [
        { name: 'CLOSED', count: 74 },
        { name: 'IN_PROGRESS', count: 62 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 94 },
        { name: 'STANDARD', count: 42 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 44 },
        { name: 'REQUIRED', count: 92 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 9 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 9 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 43 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 17 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 21 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 36 },
        { name: 'UNSPECIFIED', count: 1 },
      ],
    },
  },
  {
    id: 48,
    name: 'Kootenay',
    province: 'BC',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 1 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 1 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 1 },
        { name: 'FINANCIAL', count: 2 },
        { name: 'INTEGRITY_MANAGEMENT', count: 2 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 4 },
        { name: 'SUNSET_CLAUSE', count: 1 },
      ],
      status: [
        { name: 'CLOSED', count: 9 },
        { name: 'IN_PROGRESS', count: 0 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 5 },
        { name: 'STANDARD', count: 4 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 4 },
        { name: 'REQUIRED', count: 5 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 1 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 3 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 4 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 1 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 49,
    name: 'Parklands',
    province: 'MB',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 2 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 4 },
        { name: 'FINANCIAL', count: 0 },
        { name: 'INTEGRITY_MANAGEMENT', count: 2 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 8 },
        { name: 'SUNSET_CLAUSE', count: 3 },
      ],
      status: [
        { name: 'CLOSED', count: 15 },
        { name: 'IN_PROGRESS', count: 0 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 7 },
        { name: 'STANDARD', count: 8 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 10 },
        { name: 'REQUIRED', count: 5 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 1 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 3 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 6 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 0 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 2 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 3 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 50,
    name: 'Lower Mainland--Southwest',
    province: 'BC',
    aggregatedCount: {
      instrument: [
        { name: 'GC', count: 13 },
        { name: 'OPL', count: 4 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 42 },
        { name: 'DAMAGE_PREVENTION', count: 2 },
        { name: 'EMERGENCY_MANAGEMENT', count: 39 },
        { name: 'ENFORCEMENT', count: 5 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 203 },
        { name: 'FINANCIAL', count: 11 },
        { name: 'INTEGRITY_MANAGEMENT', count: 105 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 10 },
        { name: 'SECURITY', count: 7 },
        { name: 'SOCIO_ECONOMIC', count: 75 },
        { name: 'STANDARD_CONDITION', count: 60 },
        { name: 'SUNSET_CLAUSE', count: 14 },
      ],
      status: [
        { name: 'CLOSED', count: 233 },
        { name: 'IN_PROGRESS', count: 296 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 471 },
        { name: 'STANDARD', count: 58 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 72 },
        { name: 'REQUIRED', count: 457 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 75 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 14 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 114 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 17 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 83 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 225 },
        { name: 'UNSPECIFIED', count: 1 },
      ],
    },
  },
  {
    id: 51,
    name: 'North Shore',
    province: 'NS',
    aggregatedCount: {
      instrument: [
        { name: 'XO', count: 7 },
        { name: 'MO', count: 12 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 3 },
        { name: 'DAMAGE_PREVENTION', count: 5 },
        { name: 'EMERGENCY_MANAGEMENT', count: 1 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 5 },
        { name: 'FINANCIAL', count: 3 },
        { name: 'INTEGRITY_MANAGEMENT', count: 8 },
        { name: 'MANAGEMENT_SYSTEM', count: 9 },
        { name: 'SAFETY_MANAGEMENT', count: 2 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 9 },
        { name: 'SUNSET_CLAUSE', count: 2 },
      ],
      status: [
        { name: 'CLOSED', count: 25 },
        { name: 'IN_PROGRESS', count: 12 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 28 },
        { name: 'STANDARD', count: 9 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 18 },
        { name: 'REQUIRED', count: 19 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 2 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 5 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 5 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 23 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 2 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
  {
    id: 52,
    name: 'Kitchener--Waterloo--Barrie',
    province: 'ON',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 2 },
        { name: 'AO', count: 3 },
        { name: 'SG', count: 0 },
        { name: 'ZO', count: 9 },
        { name: 'OTHER', count: 0 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 2 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 1 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 9 },
        { name: 'FINANCIAL', count: 2 },
        { name: 'INTEGRITY_MANAGEMENT', count: 10 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 5 },
        { name: 'STANDARD_CONDITION', count: 8 },
        { name: 'SUNSET_CLAUSE', count: 2 },
      ],
      status: [
        { name: 'CLOSED', count: 33 },
        { name: 'IN_PROGRESS', count: 1 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 26 },
        { name: 'STANDARD', count: 8 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 8 },
        { name: 'REQUIRED', count: 26 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 1 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 2 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 6 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 4 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 10 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 10 },
        { name: 'UNSPECIFIED', count: 1 },
      ],
    },
  },
  {
    id: 53,
    name: 'Yukon',
    province: 'YT',
    aggregatedCount: {
      instrument: [
        { name: 'MO', count: 4 },
        { name: 'AO', count: 2 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 1 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 0 },
        { name: 'ENFORCEMENT', count: 0 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 1 },
        { name: 'FINANCIAL', count: 2 },
        { name: 'INTEGRITY_MANAGEMENT', count: 1 },
        { name: 'MANAGEMENT_SYSTEM', count: 0 },
        { name: 'SAFETY_MANAGEMENT', count: 0 },
        { name: 'SECURITY', count: 0 },
        { name: 'SOCIO_ECONOMIC', count: 0 },
        { name: 'STANDARD_CONDITION', count: 4 },
        { name: 'SUNSET_CLAUSE', count: 1 },
      ],
      status: [
        { name: 'CLOSED', count: 8 },
        { name: 'IN_PROGRESS', count: 0 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 4 },
        { name: 'STANDARD', count: 4 },
      ],
      filing: [
        { name: 'NOT_REQUIRED', count: 4 },
        { name: 'REQUIRED', count: 4 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 0 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 1 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 3 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 3 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 1 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 0 },
        { name: 'UNSPECIFIED', count: 0 },
      ],
    },
  },
];

export default locationData;
