/* eslint-disable */
export const data = [
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":599391.6,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":68442.16,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":65664.38,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":36983.53,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":17566.82,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":42314.66,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":11795.68,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":493.1351,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":142,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":156878,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":40.879,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":178980.3,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":19736.9,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":353.134,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":594401.6,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":71783.15,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":59275.79,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":34423.1,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":17769.71,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":43054.26,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":11467.99,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":462.8529,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":145,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":156562.1,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":36.879,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":179461.1,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":19606.5,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":353.134,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":616305.6,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":72542.34,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":69444.68,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":34429.2,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":16067.48,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":41833.66,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":12576.29,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":427.8137,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":149,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":156736.3,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":40.879,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":191089.9,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":20614.9,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":353.134,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":617707.5,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":71654.46,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":63722.7,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":35561.3,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":13264.46,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":43493.25,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":12215.73,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":476.047,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":182,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":161659.1,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":147.482,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":193194.3,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":21765.6,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":371.062,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":590312.7,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":72166.98,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":60262.97,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":34185.9,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":13108.33,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":38399.21,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":11695.34,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":506.549,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":162,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":142370,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":354.721,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":195934,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":20768.9,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":397.826,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":581073,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":70346.07,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":60168.15,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":33756.9,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":11188.45,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":41942,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":11968.59,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":409.1715,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":162,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":145708,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":463,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":184147.6,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":20407.8,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":405.299,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":614571.3,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":73055.01,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":68674.24,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":35114.6,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":11884.42,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":41720.03,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":11614.73,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":380.793,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":98,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":153469.2,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":493,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":196446.7,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":21195.3,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":425.337,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":620767.7,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":75079.16,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":71670.73,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":33214.89,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":10384.79,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":43815.25,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":11105.7,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":367.926,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":98,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":152140.4,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":481.163,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":200705.3,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":21249.3,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":455.004,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":642511.1,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":78052.09,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":65223.36,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":36343.61,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":15086.21,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":43257.76,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":10769.5,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":494.708,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":98,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":159657.9,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":506.168,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":209469,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":23182,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":370.755,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":646448.5,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":84243.44,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":66890.48,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":35577.09,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":15944.88,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":41053.99,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":10640.85,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":390.3412,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":157.598,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":161893.6,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":619.58,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":205519.7,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":23082.96,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":434.002,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":639818.2,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":80423.7,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":71143.63,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":35834.34,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":13861.04,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":41839.36,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":10212.38,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":375.0889,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":157.415,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":159127.1,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":615.994,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":202351.5,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":23430.54,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":446.129,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":648714.3,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":83994.81,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":72740.09,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":36572.82,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":15245.65,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":41347.64,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":9845.573,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":387.4005,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":189.829,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":155783.7,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":602.653,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":206967.6,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":24591.85,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":444.6677,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":646395.2,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":82738.48,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":74917.59,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":37046.03,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":13226.29,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":38718.29,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":10054.32,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":401.4921,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":189.829,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":151682.3,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":609.1119,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":211300.3,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":25028.91,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":482.1497,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":648193.7,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":81171.27,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":74289.85,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":36922.79,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":12205.1,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":42833.25,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":9645.35,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":349.6729,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":237.2484,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":151240.2,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":651.7555,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":213843.8,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":24339.09,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":464.2834,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":651220.4,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":83050.95,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":75004.63,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":36920.19,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":12192.26,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":42814.02,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":9632.74,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":354.7057,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":244.7412,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":150709.9,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":648.5748,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":214884.8,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":24242.92,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":520.002,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":656262.4,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":82253.24,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":75357.45,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":39047.65,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":12275.4,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":44661.04,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":9368.286,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":357.4666,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":256.2098,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":150793.9,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":659.1104,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":215410.8,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":25289.77,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":532.0476,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":658178.5,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":84676.58,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":75771.92,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":41716.05,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":11479.1,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":46141.34,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":7616.786,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":357.6418,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":260.0688,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":147837.1,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":766.6348,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":216751.4,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":24268.82,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":535.1064,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":649519.6,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":85394.16,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":76047.27,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":41822.09,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":10567.88,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":46180.65,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":7703.663,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":365.1289,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":263.3472,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":138630.5,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":762.4678,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":216877.7,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":24329.27,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":575.4511,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":649769.9,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":86646.76,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":76868.41,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":41822.98,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":10841.59,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":46219.92,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":7777.186,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":367.7275,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":268.7851,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":136251.2,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":743.644,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":216877.5,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":24490.02,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":594.2391,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":655945.7,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":87789.55,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":77481.72,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":41899.03,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":10744.65,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":46249.62,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":7933.832,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":366.4982,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":272.1072,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":140219.7,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":748.6829,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":216895,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":24761.08,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":584.2111,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":658090.5,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":88851.06,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":83033.36,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":41899.92,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":10675.71,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":46288.02,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":8146.23,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":367.5524,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":273.8616,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":134181.9,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":831.3423,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":217771.3,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":25187.34,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":582.8947,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":665437.7,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":90532.7,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":84276.41,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":42143.45,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":10294.82,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":46302.98,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":8265.898,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":368.9069,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":277.5451,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":138530,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":860.8528,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":217897.2,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":25116.55,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":570.3747,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":674895.6,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":91763.91,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":86644.72,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":45043.54,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":9369.26,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":46322.02,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":8298.701,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":372.6375,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":280.9989,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":138988.7,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":853.8853,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":221084.2,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":25297.58,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":575.4511,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":686824.5,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":92570.93,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":87470.34,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":45061.91,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":9156.812,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":46333.81,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":8299.071,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":372.7248,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":283.6699,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":147545.5,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":857.1736,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":222565.9,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":25722.4,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":584.2112,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":689921.9,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":93914.77,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":87833.61,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":49401.45,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":9112.256,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":46355.97,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":8381.443,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":375.0461,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":287.1382,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":144411.7,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":870.1928,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":222566.2,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":25854.29,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":557.8872,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":700350.9,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":95883.56,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":88330.22,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":49396.39,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":9340.74,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":46378.8,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":8444.619,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":377.7105,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":292.4299,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":149461.2,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":956.0657,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":224948.6,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":26006.46,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":534.1543,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":703801.8,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":97524.88,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":89425.27,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":49502.38,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":9345.044,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":46415.27,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":8506.982,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":378.1913,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":293.0001,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":146852.3,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":979.5066,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":227877,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":26166.16,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":535.8151,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":709835.2,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":98429.74,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":90011.61,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":49520.77,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":9476.425,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":46456.4,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":8573.648,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":378.7623,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":297.5208,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":150954.3,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":998.7557,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":227903.3,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":26289.24,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":544.7935,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":712905.4,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":100226.5,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":90532.28,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":49626.77,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":9486.164,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":46502.79,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":8619.326,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":378.8496,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":302.0229,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":151370.2,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":1011.836,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":227903.4,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":26447.84,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":497.2697,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":718843.6,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":102022.8,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":90324.84,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":49627.64,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":9465.939,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":46560.82,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":8667.979,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":379.0685,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":301.9351,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":155468.2,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":1024.808,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":227903.4,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":26597.24,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":498.9802,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":722268.2,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":104235.4,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":90136.58,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":49628.52,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":9462.663,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":46621.98,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":8713.896,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":380.1168,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":304.6939,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":156424.5,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":1039.873,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":228059.9,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":26756.69,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":503.3652,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":724632.1,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":106324.2,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":90254.73,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":49277.61,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":9478.61,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":46696.82,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":8746.086,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":380.1604,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":310.9147,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":156619.2,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":1052.375,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":228085.9,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":26901.75,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":503.6285,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":727630.6,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":107903.1,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":90750.95,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":49284.39,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":9474.787,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":46762.01,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":8784.043,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":381.2145,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":314.0681,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":157254.5,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":1066.045,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":228086,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":27061.59,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":507.8714,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":731186.1,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":109713,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":91292.03,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":49439.26,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":9475.889,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":46840.26,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":8828.017,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":384.2865,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":321.1655,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":157637.5,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":1075.991,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":228436.5,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":27232.5,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":509.7096,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":734421.7,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":111264.9,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":91741.74,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":49650.02,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":9486.014,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":46911.46,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":8858.025,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":384.2866,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":323.1786,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":157883.8,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":1083.954,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":228852.5,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":27472.06,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":509.7972,
    "unit":"GW.h"
  },
  {
    "province":"all",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":737322.9,
    "unit":"GW.h"
  },
  {
    "province":"AB",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":112777.7,
    "unit":"GW.h"
  },
  {
    "province":"BC",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":92138.2,
    "unit":"GW.h"
  },
  {
    "province":"MB",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":49707.07,
    "unit":"GW.h"
  },
  {
    "province":"NB",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":9333.143,
    "unit":"GW.h"
  },
  {
    "province":"NL",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":46970.1,
    "unit":"GW.h"
  },
  {
    "province":"NS",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":8887.08,
    "unit":"GW.h"
  },
  {
    "province":"NT",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":384.3739,
    "unit":"GW.h"
  },
  {
    "province":"NU",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":331.8069,
    "unit":"GW.h"
  },
  {
    "province":"ON",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":158242.3,
    "unit":"GW.h"
  },
  {
    "province":"PE",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":1095.184,
    "unit":"GW.h"
  },
  {
    "province":"QC",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":229294.8,
    "unit":"GW.h"
  },
  {
    "province":"SK",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":27646.61,
    "unit":"GW.h"
  },
  {
    "province":"YT",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":514.5809,
    "unit":"GW.h"
  }
];
