const rawData = [
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":10521.0145,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":2792.7536,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":1248.2454,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":291.6187,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":257.1329,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":164.8921,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":203.4443,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":18.0027,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":3.566,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":3076.8644,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":25.2844,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":1871.2434,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":559.898,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2005,
    "value":8.068,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":10477.9234,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":2941.3503,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":1218.561,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":278.8887,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":257.3801,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":167.5671,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":198.9287,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":18.0061,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":4.7813,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":2968.1336,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":24.1699,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":1848.8183,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":542.6294,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2006,
    "value":8.7082,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":10854.4259,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":3110.3262,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":1220.6337,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":294.8279,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":271.7129,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":182.4097,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":213.7254,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":24.1052,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":5.3546,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":3016.8085,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":25.6998,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":1903.6527,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":576.1471,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2007,
    "value":9.0215,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":10614.4724,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":2999.2427,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":1162.9028,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":294.543,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":251.8043,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":175.0861,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":206.8967,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":21.2393,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":4.917,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":3010.6328,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":24.7772,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":1856.4919,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":596.9668,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2008,
    "value":8.9717,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":10288.8058,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":3036.1867,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":1118.1304,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":283.8003,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":256.7589,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":165.3266,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":203.7988,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":15.1461,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":4.7698,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":2771.5512,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":24.9719,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":1800.6534,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":599.3118,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2009,
    "value":8.3999,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":10542.6157,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":3150.9611,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":1133.763,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":280.7218,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":281.073,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":166.0717,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":207.1135,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":16.5844,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":5.0361,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":2902.8322,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":25.5492,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":1756.4171,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":607.3119,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2010,
    "value":9.1814,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":10890.2551,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":3310.8447,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":1122.8758,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":288.5611,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":298.8535,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":165.7949,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":217.116,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":18.8849,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":5.507,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":3003.1577,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":28.9761,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":1786.4402,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":633.6094,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2011,
    "value":9.6323,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":11051.041,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":3559.2002,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":1151.6462,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":304.7996,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":286.5691,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":154.978,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":204.3576,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":17.9175,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":5.8916,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":2950.2093,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":27.5201,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":1746.6797,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":631.3499,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2012,
    "value":9.9214,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":11227.7889,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":3638.201,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":1173.0242,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":311.3517,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":239.4731,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":153.0596,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":196.0026,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":17.0792,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":6.1659,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":3039.5196,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":26.0173,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":1776.2672,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":643.1275,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2013,
    "value":8.5005,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":11314.4505,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":3662.4023,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":1170.4282,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":317.305,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":228.0844,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":163.8907,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":168.3214,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":19.6295,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":6.159,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":3085.5995,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":25.8072,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":1771.7305,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":687.1712,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2014,
    "value":7.9211,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":11343.8802,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":3674.7731,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":1162.0149,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":318.4137,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":226.5848,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":166.803,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":177.6324,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":21.9625,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":5.7142,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":3069.2594,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":26.391,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":1799.1034,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":686.8642,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2015,
    "value":8.363,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":11297.6196,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":3684.9028,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":1209.4481,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":314.5606,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":232.2012,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":171.9139,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":169.9124,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":21.2728,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":7.1105,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":3016.401,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":27.1079,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":1770.5071,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":663.951,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2016,
    "value":8.3304,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":11509.2471,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":3816.8521,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":1249.0937,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":322.9313,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":230.3728,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":162.3055,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":169.2315,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":21.3186,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":6.6031,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":3039.2293,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":27.4031,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":1773.6359,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":682.3555,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2017,
    "value":7.9135,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":11705.9854,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":3925.3795,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":1270.7123,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":323.4341,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":229.1781,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":157.3503,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":165.2332,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":20.7765,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":6.412,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":3096.2674,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":27.3456,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":1787.7545,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":688.6563,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2018,
    "value":7.4858,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":11777.3291,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":4018.4378,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":1263.9488,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":322.5142,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":225.8162,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":159.5064,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":163.7099,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":20.6069,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":6.7986,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":3097.7639,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":27.247,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":1775.198,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":687.2216,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2019,
    "value":8.5596,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":11800.5732,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":4067.4711,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":1254.4589,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":322.1097,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":224.0189,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":154.8677,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":162.8307,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":20.7833,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":7.2946,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":3089.4318,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":27.2189,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":1771.1197,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":690.2123,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2020,
    "value":8.7567,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":11853.6139,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":4129.8638,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":1249.8283,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":320.6514,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":221.8441,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":155.8392,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":162.1653,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":20.2487,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":7.3416,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":3082.6811,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":27.125,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":1776.7141,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":690.5873,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2021,
    "value":8.7229,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":11899.3589,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":4179.8134,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":1244.626,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":318.599,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":219.9265,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":155.2108,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":161.2492,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":19.7038,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":7.4784,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":3090.1873,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":26.9275,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":1779.5716,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":686.5937,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2022,
    "value":9.4688,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":11940.1507,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":4216.4586,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":1243.8349,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":317.1366,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":218.27,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":155.0517,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":160.2297,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":19.16,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":7.6507,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":3098.5868,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":26.7536,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":1782.9874,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":684.2374,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2023,
    "value":9.7928,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":11956.0423,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":4225.1467,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":1258.4206,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":315.8511,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":216.9206,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":153.8182,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":159.3057,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":18.6917,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":7.7947,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":3096.861,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":26.6203,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":1784.8405,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":682.242,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2024,
    "value":9.5283,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":11980.7324,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":4237.9753,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":1285.9678,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":315.6972,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":215.3728,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":151.1147,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":158.243,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":18.2857,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":7.8513,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":3091.7708,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":26.5465,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":1783.2896,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":679.2417,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2025,
    "value":9.3761,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":12045.2088,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":4273.8658,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":1327.4756,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":315.7393,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":214.0594,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":147.3262,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":156.9827,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":17.9075,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":7.9034,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":3088.8686,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":26.4455,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":1780.4161,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":679.1355,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2026,
    "value":9.0828,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":12064.4487,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":4285.9457,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":1341.2135,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":316.2466,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":213.7177,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":146.543,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":155.8957,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":17.5499,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":7.957,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":3087.127,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":26.4009,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":1777.7678,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":678.951,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2027,
    "value":9.1332,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":12065.8348,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":4288.3276,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":1345.8521,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":316.7428,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":212.9097,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":143.8319,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":154.9917,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":17.1928,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":8.0279,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":3088.3565,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":26.3981,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":1777.4223,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":676.5276,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2028,
    "value":9.2542,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":12068.7103,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":4292.2404,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":1349.1387,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":317.0742,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":212.3926,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":143.307,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":154.0691,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":16.8728,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":8.0954,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":3088.5914,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":26.414,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":1777.2172,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":674.7064,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2029,
    "value":8.5906,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":12112.8582,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":4315.8176,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":1370.479,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":317.4448,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":211.1301,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":140.9712,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":153.1677,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":16.5283,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":8.1761,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":3092.3455,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":26.4586,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":1778.5743,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":673.7466,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2030,
    "value":8.0167,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":12175.6505,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":4346.4614,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":1399.9352,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":317.6148,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":210.4301,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":139.6441,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":152.2961,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":16.2352,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":8.2634,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":3096.5415,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":26.6004,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":1780.2876,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":673.3385,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2031,
    "value":8.0024,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":12203.9914,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":4354.0642,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":1419.5893,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":317.6683,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":209.7629,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":138.113,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":151.4404,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":15.962,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":8.3535,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":3099.7784,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":26.6698,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":1781.8146,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":672.642,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2032,
    "value":8.134,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":12201.0864,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":4350.7939,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":1418.2957,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":317.6813,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":208.9687,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":137.9861,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":150.634,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":15.7284,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":8.4539,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":3103.0107,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":26.755,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":1782.9371,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":672.8672,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2033,
    "value":6.9745,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":12198.6882,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":4350.5634,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":1415.5227,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":317.621,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":208.1923,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":137.8238,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":149.7882,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":15.4945,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":8.3188,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":3104.9176,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":26.8404,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":1783.2415,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":673.3664,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2034,
    "value":6.9964,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":12203.7249,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":4356.0618,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":1413.9827,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":317.6273,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":207.389,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":138.3769,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":148.8682,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":15.2725,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":8.4351,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":3106.6215,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":26.92,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":1782.9302,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":674.2196,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2035,
    "value":7.0207,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":12199.7146,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":4355.2891,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":1412.0396,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":317.6176,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":206.5374,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":138.0101,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":147.9093,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":15.0662,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":8.5565,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":3107.2119,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":26.9984,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":1782.1433,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":675.2892,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2036,
    "value":7.0455,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":12192.3609,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":4353.2249,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":1409.928,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":317.7423,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":205.6377,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":137.0336,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":146.9484,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":14.869,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":8.6828,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":3106.627,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":27.0572,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":1780.8791,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":676.6681,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2037,
    "value":7.0625,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":12191.4954,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":4357.8837,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":1408.74,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":317.8403,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":204.7239,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":135.6682,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":146.0556,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":14.6917,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":8.816,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":3105.4478,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":27.1047,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":1779.3068,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":678.135,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2038,
    "value":7.0824,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":12189.4172,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":4362.3692,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":1408.0303,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":318.0991,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":203.8152,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":134.3147,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":145.0661,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":14.5301,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":8.9554,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":3103.5763,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":27.132,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":1776.4,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":680.0249,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2039,
    "value":7.1031,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":12183.1165,
    "unit":"Petajoules"
  },
  {
    "province":"AB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":4363.0014,
    "unit":"Petajoules"
  },
  {
    "province":"BC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":1407.7448,
    "unit":"Petajoules"
  },
  {
    "province":"MB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":318.2461,
    "unit":"Petajoules"
  },
  {
    "province":"NB",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":202.7873,
    "unit":"Petajoules"
  },
  {
    "province":"NL",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":132.6007,
    "unit":"Petajoules"
  },
  {
    "province":"NS",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":144.0825,
    "unit":"Petajoules"
  },
  {
    "province":"NT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":14.3824,
    "unit":"Petajoules"
  },
  {
    "province":"NU",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":9.0937,
    "unit":"Petajoules"
  },
  {
    "province":"ON",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":3101.2197,
    "unit":"Petajoules"
  },
  {
    "province":"PE",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":27.1671,
    "unit":"Petajoules"
  },
  {
    "province":"QC",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":1773.6833,
    "unit":"Petajoules"
  },
  {
    "province":"SK",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":681.9808,
    "unit":"Petajoules"
  },
  {
    "province":"YT",
    "sector":"total",
    "source":"total",
    "scenario":"reference",
    "year":2040,
    "value":7.1257,
    "unit":"Petajoules"
  },
];

export default rawData;
