const rawData = [
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2005,
    "value":1831.5111,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2006,
    "value":1811.0809,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2007,
    "value":1851.4284,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2008,
    "value":1851.3623,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2009,
    "value":1768.9455,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2010,
    "value":1789.4012,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2011,
    "value":1830.7513,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2012,
    "value":1823.8419,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2013,
    "value":1852.1626,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2014,
    "value":1891.5148,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2015,
    "value":1882.6489,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2016,
    "value":1894.3845,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2017,
    "value":1916.2076,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2018,
    "value":1941.0065,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2019,
    "value":1947.0396,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2020,
    "value":1963.6014,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2021,
    "value":1985.1093,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2022,
    "value":2005.9023,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2023,
    "value":2028.5981,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2024,
    "value":2050.3355,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2025,
    "value":2071.6943,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2026,
    "value":2094.2476,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2027,
    "value":2112.8468,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2028,
    "value":2130.7687,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2029,
    "value":2148.716,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2030,
    "value":2169.5182,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2031,
    "value":2191.7629,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2032,
    "value":2212.1179,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2033,
    "value":2230.1178,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2034,
    "value":2246.3799,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2035,
    "value":2263.8926,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2036,
    "value":2280.597,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2037,
    "value":2296.8899,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2038,
    "value":2313.495,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2039,
    "value":2328.469,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"electricity",
    "scenario":"reference",
    "year":2040,
    "value":2342.8501,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2005,
    "value":4568.1404,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2006,
    "value":4610.0437,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2007,
    "value":4739.1802,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2008,
    "value":4605.1977,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2009,
    "value":4492.0295,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2010,
    "value":4695.5686,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2011,
    "value":4729.0223,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2012,
    "value":4838.1894,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2013,
    "value":4747.9889,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2014,
    "value":4641.5326,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2015,
    "value":4687.3823,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2016,
    "value":4683.6815,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2017,
    "value":4713.4095,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2018,
    "value":4749.2792,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2019,
    "value":4744.0166,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2020,
    "value":4703.542,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2021,
    "value":4710.7884,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2022,
    "value":4727.3217,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2023,
    "value":4715.4277,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2024,
    "value":4693.7249,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2025,
    "value":4668.8084,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2026,
    "value":4651.3471,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2027,
    "value":4635.7126,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2028,
    "value":4619.369,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2029,
    "value":4602.3857,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2030,
    "value":4589.6971,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2031,
    "value":4579.1116,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2032,
    "value":4565.8049,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2033,
    "value":4551.7471,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2034,
    "value":4538.4578,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2035,
    "value":4526.139,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2036,
    "value":4511.1102,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2037,
    "value":4496.9268,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2038,
    "value":4484.0133,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2039,
    "value":4471.0684,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"oilProducts",
    "scenario":"reference",
    "year":2040,
    "value":4459.0128,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2005,
    "value":645.7682,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2006,
    "value":592.6285,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2007,
    "value":604.467,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2008,
    "value":554.2876,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2009,
    "value":526.3304,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2010,
    "value":545.5212,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2011,
    "value":557.4661,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2012,
    "value":558.8121,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2013,
    "value":591.7115,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2014,
    "value":591.5593,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2015,
    "value":624.2472,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2016,
    "value":619.4215,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2017,
    "value":632.4372,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2018,
    "value":643.0262,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2019,
    "value":642.3961,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2020,
    "value":644.9873,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2021,
    "value":643.6276,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2022,
    "value":642.4158,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2023,
    "value":641.4932,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2024,
    "value":641.3703,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2025,
    "value":639.9451,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2026,
    "value":638.9519,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2027,
    "value":638.4547,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2028,
    "value":638.0205,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2029,
    "value":636.876,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2030,
    "value":635.591,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2031,
    "value":633.8431,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2032,
    "value":631.7097,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2033,
    "value":629.2578,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2034,
    "value":626.4116,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2035,
    "value":623.6301,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2036,
    "value":620.6471,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2037,
    "value":617.5717,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2038,
    "value":614.4892,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2039,
    "value":611.5132,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"bio",
    "scenario":"reference",
    "year":2040,
    "value":608.566,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2005,
    "value":3232.8801,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2006,
    "value":3221.4859,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2007,
    "value":3426.2401,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2008,
    "value":3379.8784,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2009,
    "value":3311.235,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2010,
    "value":3327.6063,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2011,
    "value":3558.0784,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2012,
    "value":3631.0415,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2013,
    "value":3853.3945,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2014,
    "value":3996.7164,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2015,
    "value":3983.9174,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2016,
    "value":3933.6387,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2017,
    "value":4076.2474,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2018,
    "value":4195.7743,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2019,
    "value":4266.1685,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2020,
    "value":4310.4237,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2021,
    "value":4335.648,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2022,
    "value":4344.0795,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2023,
    "value":4373.2718,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2024,
    "value":4387.796,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2025,
    "value":4417.768,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2026,
    "value":4478.2306,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2027,
    "value":4494.6472,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2028,
    "value":4494.0718,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2029,
    "value":4496.5515,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2030,
    "value":4533.2736,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2031,
    "value":4585.6383,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2032,
    "value":4608.5707,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2033,
    "value":4603.6903,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2034,
    "value":4600.7956,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2035,
    "value":4603.0686,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2036,
    "value":4600.0595,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2037,
    "value":4593.3353,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2038,
    "value":4591.4928,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2039,
    "value":4589.9854,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"naturalGas",
    "scenario":"reference",
    "year":2040,
    "value":4583.9054,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2005,
    "value":242.7147,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2006,
    "value":242.6844,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2007,
    "value":233.1102,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2008,
    "value":223.7464,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2009,
    "value":190.2654,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2010,
    "value":184.5184,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2011,
    "value":214.937,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2012,
    "value":199.1561,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2013,
    "value":182.5314,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2014,
    "value":193.1274,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2015,
    "value":165.6844,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2016,
    "value":166.4934,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2017,
    "value":170.9454,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2018,
    "value":176.3292,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2019,
    "value":176.4601,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2020,
    "value":176.0601,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2021,
    "value":175.7668,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2022,
    "value":176.256,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2023,
    "value":177.2469,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2024,
    "value":177.9702,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2025,
    "value":176.9417,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2026,
    "value":176.1367,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2027,
    "value":175.784,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2028,
    "value":175.9007,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2029,
    "value":175.7802,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2030,
    "value":175.6823,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2031,
    "value":175.5083,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2032,
    "value":175.3162,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2033,
    "value":175.1251,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2034,
    "value":174.8417,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2035,
    "value":174.5558,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2036,
    "value":174.2469,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2037,
    "value":173.9881,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2038,
    "value":173.784,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2039,
    "value":173.6079,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"coal",
    "scenario":"reference",
    "year":2040,
    "value":173.4774,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2005,
    "value":0,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2006,
    "value":0,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2007,
    "value":0,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2008,
    "value":0,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2009,
    "value":0,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2010,
    "value":0,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2011,
    "value":0,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2012,
    "value":0,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2013,
    "value":0,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2014,
    "value":0,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2015,
    "value":0,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2016,
    "value":0,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2017,
    "value":0,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2018,
    "value":0.57,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2019,
    "value":1.2482,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2020,
    "value":1.9587,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2021,
    "value":2.6738,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2022,
    "value":3.3836,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2023,
    "value":4.113,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2024,
    "value":4.8454,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2025,
    "value":5.5749,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2026,
    "value":6.2949,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2027,
    "value":7.0034,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2028,
    "value":7.7041,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2029,
    "value":8.4009,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2030,
    "value":9.096,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2031,
    "value":9.7863,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2032,
    "value":10.472,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2033,
    "value":11.1483,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2034,
    "value":11.8016,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2035,
    "value":12.4388,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2036,
    "value":13.0539,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2037,
    "value":13.6491,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2038,
    "value":14.2211,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2039,
    "value":14.7733,
    "unit":"Petajoules"
  },
  {
    "province":"all",
    "sector":"total",
    "source":"solarWindGeothermal",
    "scenario":"reference",
    "year":2040,
    "value":15.3048,
    "unit":"Petajoules"
  },
];

export default rawData;
